# -*- coding: utf-8 -*-
"""Money_Changer_APK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOG_MVkaoezmyIb9B0pfWcDpALl0YA2y
"""

import ipywidgets as widgets
from IPython.display import display

# 1. Membuat Database Kurs Mata Uang
KURS = {
    'IDR (Rupiah)': 1.0,
    'USD (Dolar AS)': 18099.0,
    'SGD (Dolar Singapura)': 13992.0,
    'EUR (Euro)': 20677.0,
    'JPY (Yen Jepang)': 111.53,
    'MYR (Ringgit Malaysia)': 4439.54
}

# 2. Membuat Komponen Antarmuka (Input dan Tombol)
MataUangAsal = widgets.Dropdown(
    options=list(KURS.keys()),
    value='USD (Dolar AS)',
    description='Dari:',
    layout=widgets.Layout(width='95%', margin='5px')
)

MataUangTujuan = widgets.Dropdown(
    options=list(KURS.keys()),
    value='IDR (Rupiah)',
    description='Ke:',
    layout=widgets.Layout(width='95%', margin='5px')
)

JumlahInput = widgets.FloatText(
    value=1.0,
    description='Jumlah:',
    layout=widgets.Layout(width='95%', margin='5px')
)

TombolHitung = widgets.Button(
    description='KONVERSI',
    layout=widgets.Layout(width='95%', height='40px', margin='15px 5px 5px 5px')
)
# Warna tombol
TombolHitung.style.button_color = '#00E676'
TombolHitung.style.text_color = '#121212'
TombolHitung.style.font_weight = 'bold'

# Tempat Menampilakn Hasil Konversi
OutputHasil = widgets.Label(
    value="Silakan masukkan angka dan klik Konversi",
    layout=widgets.Layout(margin='15px 5px 5px 5px', justify_content='center')
)
OutputHasil.style.text_color = '#FFD700'

# 3. Database Konversi
def konversi_uang(b):
    asal = MataUangAsal.value
    tujuan = MataUangTujuan.value
    jumlah = JumlahInput.value

    if jumlah <= 0:
        OutputHasil.style.text_color = '#FF5252' # Merah terang jika error
        OutputHasil.value = "❌ Peringatan: Jumlah harus lebih besar dari 0!"
        return

    # Penghitungan Konversi
    jumlah_idr = jumlah * KURS[asal]
    hasil_konversi = jumlah_idr / KURS[tujuan]

    # Update teks langsung pada widget Label
    kode_asal = asal[:3]
    kode_tujuan = tujuan[:3]

    OutputHasil.style.text_color = '#00E5FF'
    OutputHasil.value = f"💵 Hasil: {jumlah:,.2f} {kode_asal} = {hasil_konversi:,.2f} {kode_tujuan}"

# Hubungkan tombol dengan fungsi
TombolHitung.on_click(konversi_uang)

# 4. Background Utama
JudulAplikasi = widgets.HTML(value="<h3 style='text-align:center; color:#00E5FF; margin:0;'>MONEY CHANGER APK</h3>")

# Menggabungkan semua komponen ke dalam VBox (Vertical Box)
AplikasiKontainer = widgets.VBox(
    [JudulAplikasi, JumlahInput, MataUangAsal, MataUangTujuan, TombolHitung, OutputHasil],
    layout=widgets.Layout(
        width='400px',
        background_color='#1E1E1E',
        border='2px solid #00E5FF',
        padding='20px',
        border_radius='12px',
        align_items='center'
    )
)

# Tampilan Akhir
display(AplikasiKontainer)